task:
  name: Deploy
  stateful: true
  timeout_in: 120m
  env:
    CIRRUS_WORKING_DIR: "/tmp/ci"
    SECRET_TOKEN: ENCRYPTED[394af87d0a327057c04e5751079529637922859fe4e9a2b3a088a8dddc30e6325f15036c78b7ec8203ea98d322384986]
    accountsfile: ENCRYPTED[acf7738eb18bbf80182ad22be8fd2a2a48e670c023e1713bb58867be40c9469d3de529729197a9bbb7ca9be72501a04c]
    DEBIAN_FRONTEND: noninteractive
    LANGUAGE: en_US.UTF-8
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LC_CTYPE: en_US.UTF-8
  container:
    dockerfile: Dockerfile
    cpu: 6
    memory: 6G
        
  update_background_script:
    - bash update.sh
    
  start_script:
    - bash start.sh
